### ISSUE TITLE
Opening an AVI-file returns exception

### ISSUE THREAD

**Issue by GoogleCodeExporter** [0xfab-ri/universal-media-server#11]
```
What steps will reproduce the problem?
1. Playing an avi file on a PlayStation 3

What is the expected output? What do you see instead?
UMS Log output:
ERROR 2012-07-20 21:43:46.908 [tsMuxeR-19] Fatal error in process 
initialization: 
java.io.IOException: Cannot run program "tsMuxeR": error=2, No such file or 
directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029) ~[na:1.7.0_05]
    at net.pms.io.ProcessWrapperImpl.run(ProcessWrapperImpl.java:131) ~[ums.jar:na]
Caused by: java.io.IOException: error=2, No such file or directory
    at java.lang.UNIXProcess.forkAndExec(Native Method) ~[na:1.7.0_05]
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:135) ~[na:1.7.0_05]
    at java.lang.ProcessImpl.start(ProcessImpl.java:130) ~[na:1.7.0_05]
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1021) ~[na:1.7.0_05]
    ... 1 common frames omitted

What version of the product are you using? On what operating system?
UMS 1.4.0 on Ubuntu 12.04
Before i had UMS 1.1.1 and it worked.

Please provide any additional information below.
```

Original issue reported on code.google.com by `raulmari...@gmail.com` on 20 Jul 2012 at 7:51

**Comment by GoogleCodeExporter** [comment]
```
I've deleted all the local data folders. I believe there is only one that saves 
your settings. So I tried it with a clean, new execution. It seems this 
exception comes only, if i try to play an avi file on the PlayStation 3. There 
is no problem, if i play it directly from my Samsung UE46D6500 LED TV. Hope 
this helps.
```

Original comment by `raulmari...@gmail.com` on 2 Aug 2012 at 3:01

**Comment by GoogleCodeExporter** [comment]
```
Hi, please try it with the latest version and let me know if it's fixed or not
```

Original comment by `subjunk` on 20 Nov 2012 at 11:59

**Comment by GoogleCodeExporter** [comment]
Original comment by `subjunk` on 6 May 2013 at 5:23
- Changed state: **Invalid**

**Comment by GoogleCodeExporter** [comment]
```
Sorry my comment comes late. It's fixed! Thanks.
```

Original comment by `raulmari...@gmail.com` on 11 May 2013 at 11:42

**Comment by GoogleCodeExporter** [comment]
```
Great, thanks for confirming :)
```

Original comment by `subjunk` on 12 May 2013 at 10:56
- Changed state: **Fixed**
