### ISSUE TITLE
NullPointerException when trying to browse with WMP

### ISSUE THREAD

**Issue by GoogleCodeExporter** [0xfab-ri/universal-media-server#12]
```
What steps will reproduce the problem?
1. Fresh install of UMS
2. add folder to shares
3. notice WMP rederer found
4. open other libraries in WMP and browse video, all video. A message will 
appear saying "server refused access"

What is the expected output? What do you see instead?
Should show the files instead gives that error

What version of the product are you using? On what operating system?

WMP 12.0.7601.17514
UMS 1.4.0
Windows 7 Ultimate 64bit

Please provide any additional information below.

In the provided log you can see the NullPointerExceptions:

DEBUG 2012-08-10 20:55:38.210 [New I/O server worker #1-2] Caught exception
java.lang.NullPointerException: null
    at net.pms.network.RequestV2.answer(RequestV2.java:556) ~[ums.jar:na]
    at net.pms.network.RequestHandlerV2.writeResponse(RequestHandlerV2.java:298) ~[ums.jar:na]
    at net.pms.network.RequestHandlerV2.messageReceived(RequestHandlerV2.java:256) ~[ums.jar:na]
```

Original issue reported on code.google.com by `ivan.g.o...@gmail.com` on 10 Aug 2012 at 7:25

Attachments:
- [ums_dbg.zip](https://storage.googleapis.com/google-code-attachments/universal-media-server/issue-12/comment-0/ums_dbg.zip)

**Comment by GoogleCodeExporter** [comment]
```
Will be included in next release
```

Original comment by `bajen.hasse` on 11 Aug 2012 at 11:47

**Comment by GoogleCodeExporter** [comment]
```
Is this fixed now?
```

Original comment by `subjunk` on 13 Oct 2012 at 1:18
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
I think so.
```

Original comment by `bajen.hasse` on 13 Oct 2012 at 6:27

**Comment by GoogleCodeExporter** [comment]
```
I seem to get a similar issue on WMP with the same system configuration and a 
fresh install.  Either this isn't fixed, or I just coincidentally am getting 
the same symptoms.
```

Original comment by `doug.qu...@gmail.com` on 30 Oct 2012 at 1:48

**Comment by GoogleCodeExporter** [comment]
```
Still happens on Version 2.0.0
```

Original comment by `doug.qu...@gmail.com` on 3 Nov 2012 at 10:11

**Comment by GoogleCodeExporter** [comment]
```
I have fixed this for the next version.
Note that WMP doesn't (and was never supposed to) work, we only added that 
renderer because it was showing up as unknown for everyone which was annoying.
Maybe a better solution will be to just block it.
```

Original comment by `subjunk` on 3 Nov 2012 at 11:07

**Comment by GoogleCodeExporter** [comment]
```
OK in the next version of UMS, WMP will be blocked from showing up
```

Original comment by `subjunk` on 5 Nov 2012 at 5:54
- Changed state: **Fixed**
