### ISSUE TITLE
A serious error occurred during PMS init

### ISSUE THREAD

**Issue by GoogleCodeExporter** [0xfab-ri/universal-media-server#13]
```
What steps will reproduce the problem?
1. Start the program
2.
3.

What is the expected output? What do you see instead?

java.lang.IndexOutOfBoundsException: The row index 5 must be less than or equal 
to 4.
    at com.jgoodies.forms.layout.CellConstraints.ensureValidGridBounds(CellConstraints.java:949) ~[ums.jar:na]
    at com.jgoodies.forms.layout.FormLayout.setConstraints(FormLayout.java:811) ~[ums.jar:na]
    at com.jgoodies.forms.layout.FormLayout.addLayoutComponent(FormLayout.java:1094) ~[ums.jar:na]
    at java.awt.Container.addImpl(Unknown Source) ~[na:1.7.0_07]
    at java.awt.Container.add(Unknown Source) ~[na:1.7.0_07]
    at com.jgoodies.forms.builder.AbstractFormBuilder.add(AbstractFormBuilder.java:491) ~[ums.jar:na]
    at com.jgoodies.forms.builder.PanelBuilder.add(PanelBuilder.java:809) ~[ums.jar:na]
    at net.pms.encoders.FFMpegVideo.config(FFMpegVideo.java:484) ~[ums.jar:na]
    at net.pms.encoders.FFMpegVideo.config(FFMpegVideo.java:439) ~[ums.jar:na]
    at net.pms.newgui.TreeNodeSettings.getConfigPanel(TreeNodeSettings.java:79) ~[ums.jar:na]
    at net.pms.newgui.TranscodingTab.addEngines(TranscodingTab.java:309) ~[ums.jar:na]
    at net.pms.newgui.LooksFrame.addEngines(LooksFrame.java:445) ~[ums.jar:na]
    at net.pms.PMS.init(PMS.java:452) [ums.jar:na]
    at net.pms.PMS.createInstance(PMS.java:804) [ums.jar:na]
    at net.pms.PMS.main(PMS.java:877) [ums.jar:na]


What version of the product are you using? On what operating system?

1.5.0 Build Date 2012-09-03 Windows 7 64bit

Please provide any additional information below.

Worked fine before the build.
```

Original issue reported on code.google.com by `hardly...@gmail.com` on 3 Sep 2012 at 4:39

**Comment by GoogleCodeExporter** [comment]
```
I think this is fixed now, can you confirm the fix?
```

Original comment by `subjunk` on 22 Jan 2013 at 10:52
- Changed state: **Fixed**
