### ISSUE TITLE
RAR/ZIP files

### ISSUE THREAD

**Issue by GoogleCodeExporter** [0xfab-ri/universal-media-server#33]
```
What steps will reproduce the problem?
1. Trying to play a video thats rar'd/zipped 
2.
3.

What is the expected output? What do you see instead?
HTTP error 500


What version of the product are you using? On what operating system?
UMS 2.2.2 Windows 7 x64


Please provide any additional information below.

This issue started from release 2.2.1 and is still present in 2.2.2.
2.2.0 worked just fine.....

See output below

DEBUG 2013-01-05 10:34:02.236 [Rar Extractor] Unpack error, maybe it's normal, 
as backend can be terminated: unkownError
INFO  2013-01-05 10:34:04.134 [New I/O server worker #1-2] Starting 
transcode/remux of American.Horror.Story.S02E10.HDTV.x264-LOL.mp4
DEBUG 2013-01-05 10:34:04.188 [New I/O server worker #1-2] Caught exception
java.lang.NullPointerException: null
    at net.pms.encoders.MEncoderVideo.launchTranscode(MEncoderVideo.java:1349) ~[ums.jar:2.2.2]
    at net.pms.dlna.DLNAResource.getInputStream(DLNAResource.java:1737) ~[ums.jar:2.2.2]
    at net.pms.network.RequestV2.answer(RequestV2.java:326) ~[ums.jar:2.2.2]
    at net.pms.network.RequestHandlerV2.writeResponse(RequestHandlerV2.java:313) ~[ums.jar:2.2.2]
    at net.pms.network.RequestHandlerV2.messageReceived(RequestHandlerV2.java:270) ~[ums.jar:2.2.2]
    at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:149) ~[ums.jar:2.2.2]
    at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:116) ~[ums.jar:2.2.2]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:302) ~[ums.jar:2.2.2]
    at org.jboss.netty.handler.codec.replay.ReplayingDecoder.unfoldAndFireMessageReceived(ReplayingDecoder.java:527) ~[ums.jar:2.2.2]
    at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:506) ~[ums.jar:2.2.2]
    at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:443) ~[ums.jar:2.2.2]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274) ~[ums.jar:2.2.2]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261) ~[ums.jar:2.2.2]
    at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:351) ~[ums.jar:2.2.2]
    at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:282) ~[ums.jar:2.2.2]
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:202) ~[ums.jar:2.2.2]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.7.0_09]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.7.0_09]
    at java.lang.Thread.run(Unknown Source) [na:1.7.0_09]
INFO  2013-01-05 10:34:04.194 [New I/O server worker #1-3] Starting 
transcode/remux of American.Horror.Story.S02E10.HDTV.x264-LOL.mp4
DEBUG 2013-01-05 10:34:04.202 [New I/O server worker #1-3] Caught exception
java.lang.NullPointerException: null
    at net.pms.encoders.MEncoderVideo.launchTranscode(MEncoderVideo.java:1349) ~[ums.jar:2.2.2]
    at net.pms.dlna.DLNAResource.getInputStream(DLNAResource.java:1737) ~[ums.jar:2.2.2]
    at net.pms.network.RequestV2.answer(RequestV2.java:326) ~[ums.jar:2.2.2]
    at net.pms.network.RequestHandlerV2.writeResponse(RequestHandlerV2.java:313) ~[ums.jar:2.2.2]
    at net.pms.network.RequestHandlerV2.messageReceived(RequestHandlerV2.java:270) ~[ums.jar:2.2.2]
    at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:149) ~[ums.jar:2.2.2]
    at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:116) ~[ums.jar:2.2.2]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:302) ~[ums.jar:2.2.2]
    at org.jboss.netty.handler.codec.replay.ReplayingDecoder.unfoldAndFireMessageReceived(ReplayingDecoder.java:527) ~[ums.jar:2.2.2]
    at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:506) ~[ums.jar:2.2.2]
    at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:443) ~[ums.jar:2.2.2]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274) ~[ums.jar:2.2.2]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261) ~[ums.jar:2.2.2]
    at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:351) ~[ums.jar:2.2.2]
    at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:282) ~[ums.jar:2.2.2]
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:202) ~[ums.jar:2.2.2]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.7.0_09]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.7.0_09]
    at java.lang.Thread.run(Unknown Source) [na:1.7.0_09]


```

Original issue reported on code.google.com by `richards...@gmail.com` on 5 Jan 2013 at 11:55

**Comment by GoogleCodeExporter** [comment]
```
Is this still happening in 2.2.5?
```

Original comment by `subjunk` on 19 Jan 2013 at 10:17

**Comment by GoogleCodeExporter** [comment]
```
The http error that I used to get is now gone in 2.2.6 but the video playback 
stutters the sound however is fine......
```

Original comment by `richards...@gmail.com` on 23 Jan 2013 at 5:58

**Comment by GoogleCodeExporter** [comment]
Original comment by `subjunk` on 15 Mar 2013 at 11:30
- Changed state: **Fixed**
