### ISSUE TITLE
UMS working directory is included when setting an arbitrary path in mplayer_path configuration option

### ISSUE THREAD

**Issue by GoogleCodeExporter** [0xfab-ri/universal-media-server#46]
```
What steps will reproduce the problem?
1. set mplayer_path = <mplayer binary> in UMS.conf
2. restart UMS
3. cat debug.log | grep mplayer

What is the expected output? What do you see instead?
ERROR 2013-03-07 18:24:30.399 [main] Cannot launch MPlayer. Check the presence 
of .//usr/local/bin/mplayer
java.io.IOException: Cannot run program ".//usr/local/bin/mplayer": error=2, No 
such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029) ~[na:1.7.0_15]
        at net.pms.PMS.checkProcessExistence(PMS.java:217) [ums.jar:2.5.0]
        at net.pms.PMS.init(PMS.java:400) [ums.jar:2.5.0]
        at net.pms.PMS.createInstance(PMS.java:838) [ums.jar:2.5.0]
        at net.pms.PMS.main(PMS.java:925) [ums.jar:2.5.0]
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method) ~[na:1.7.0_15]
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:135) ~[na:1.7.0_15]
        at java.lang.ProcessImpl.start(ProcessImpl.java:130) ~[na:1.7.0_15]
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1021) ~[na:1.7.0_15]
        ... 4 common frames omitted


What version of the product are you using? On what operating system?
INFO  2013-03-07 18:24:29.213 [main] Starting Universal Media Server 2.5.0
INFO  2013-03-07 18:24:29.217 [main] Build: dd9f6a1dd (2013-03-05)
INFO  2013-03-07 18:24:29.218 [main] Java: 1.7.0_15-Oracle Corporation
INFO  2013-03-07 18:24:29.219 [main] OS: Linux 64-bit 3.2.0-37-generic


Please provide any additional information below.
Using a different mplayer binary, the workaround can be achieved, as follows:
1. remove mplayer_path configuration option from UMS.conf
2. rename (or delete) mplayer binary supplied in $PMS_PATH
3. create a symlink to the desired mplayer binary in $PMS_PATH
```

Original issue reported on code.google.com by `gsoet...@gmail.com` on 7 Mar 2013 at 7:44

**Comment by GoogleCodeExporter** [comment]
```
Thanks for this. It will be fixed in the version after 3.0.0-b1
```

Original comment by `subjunk` on 18 Oct 2013 at 10:37
- Changed state: **Fixed**
