### ISSUE TITLE
java.net.SocketException: Nessun device corrisponde

### ISSUE THREAD

**Issue by GoogleCodeExporter** [0xfab-ri/universal-media-server#76]
```
When the network is down a lot of error messages appear in the logs tab. Is 
anyone aware of that? Any workaround?

I have tried both ums and pms 1.90.1 and both opendjdk 7 and java 7 Update 21.

Ubuntu 13.04 Linux Linux-Home 3.10.7-031007-generic #201308150319 SMP Thu Aug 
15 07:20:26 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

Thanks!

java.net.SocketException: Nessun device corrisponde
at java.net.PlainDatagramSocketImpl.join(Native Method) ~[na:1.7.0_25]
at 
java.net.AbstractPlainDatagramSocketImpl.join(AbstractPlainDatagramSocketImpl.ja
va:178) ~[na:1.7.0_25]
at java.net.MulticastSocket.joinGroup(MulticastSocket.java:319) ~[na:1.7.0_25]
at net.pms.network.UPNPHelper$2.run(UPNPHelper.java:358) ~[ums.jar:2.6.5]
at java.lang.Thread.run(Thread.java:724) ~[na:1.7.0_25]
```

Original issue reported on code.google.com by `luigi.ro...@gmail.com` on 21 Aug 2013 at 9:52

**Comment by GoogleCodeExporter** [comment]
```
For a test I have switched back to PMS 1.90.1, but the same problem occurs. I 
think is the alive message that enters in some loop.

INFO 2013-08-22 10:39:15.519 [main] Using localhost address
INFO 2013-08-22 10:39:15.521 [main] Created socket: 0.0.0.0/0.0.0.0:5001
DEBUG 2013-08-22 10:39:15.700 [main] Sending ALIVE...
DEBUG 2013-08-22 10:39:15.707 [main] Error sending ALIVE message
java.io.IOException: No usable network interface found for UPnP multicast
at net.pms.network.UPNPHelper.getNewMulticastSocket(UPNPHelper.java:212) 
~[pms.jar:1.90.1]
at net.pms.network.UPNPHelper.sendAlive(UPNPHelper.java:172) ~[pms.jar:1.90.1]
at net.pms.PMS.init(PMS.java:614) ~[pms.jar:1.90.1]
at net.pms.PMS.createInstance(PMS.java:872) ~[pms.jar:1.90.1]
at net.pms.PMS.main(PMS.java:949) ~[pms.jar:1.90.1]
INFO 2013-08-22 10:39:15.961 [main] The server should now appear on your 
renderer
ERROR 2013-08-22 10:39:15.968 [UPNPHelper] UPNP network exception
java.net.SocketException: Nessun device corrisponde
at java.net.PlainDatagramSocketImpl.join(Native Method) ~[na:1.7.0_25]
at 
java.net.AbstractPlainDatagramSocketImpl.join(AbstractPlainDatagramSocketImpl.ja
va:178) ~[na:1.7.0_25]
at java.net.MulticastSocket.joinGroup(MulticastSocket.java:319) ~[na:1.7.0_25]
at net.pms.network.UPNPHelper$2.run(UPNPHelper.java:384) ~[pms.jar:1.90.1]
at java.lang.Thread.run(Thread.java:724) ~[na:1.7.0_25]
```

Original comment by `luigi.ro...@gmail.com` on 25 Aug 2013 at 10:47

**Comment by GoogleCodeExporter** [comment]
```
We are switching over to GitHub for our issue tracking.
Future updates to this issue will be at the following link:
https://github.com/UniversalMediaServer/UniversalMediaServer/issues/185
```

Original comment by `subjunk` on 26 Nov 2013 at 3:28
